/**
 * The release cards a build carries (SPEC-016 R-19). Under Vite this module is generated by the
 * release-cards plugin (`release-cards-plugin.ts`): the newest eight `docs/releases/<tag>/notes.md`,
 * each with the picture its front matter names, chosen before the bundler sees them — so the
 * installer never grows with the whole release history, only ever with eight pictures. Under
 * node's test runner the module is what you see here: nothing, and a test injects its own.
 */
export interface BundledCard {
  /** `v0.5.47`, as the folder is named. */
  tag: string;
  /** The card file, front matter and all. */
  notes: string;
  /** A URL the page can load, or null when the card names no picture the build carries. */
  picture: string | null;
}

export const RELEASE_CARDS: readonly BundledCard[] = [];
