// Generated by scripts/sync-hearmeman-adapters.mjs. Review source changes before activation.
import { AdapterReleaseSchema } from "@arke-studio/contracts";

export const HEARMEMAN_ADAPTERS = [
  {
    "id": "hearmeman-hmbreastsv2-d260653bdf10775380a44c8f1486bcc4690bd57085cb034002a8fb878f1ad36f",
    "adapterId": "hearmeman-hmbreasts",
    "publisher": "Hearmeman",
    "displayName": "HMBreastsV2",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMBreastsV2.safetensors",
      "bytes": 77580016,
      "sha256": "d260653bdf10775380a44c8f1486bcc4690bd57085cb034002a8fb878f1ad36f"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [
      "hearmeman-hmbreasts-085e0750-e40-039b6d5399def81c9a459d7cca8ccf749195fcb5f766f0899a387ba2fa6ad967"
    ],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmbreasts-085e0750-e40-039b6d5399def81c9a459d7cca8ccf749195fcb5f766f0899a387ba2fa6ad967",
    "adapterId": "hearmeman-hmbreasts",
    "publisher": "Hearmeman",
    "displayName": "HMBreasts_085e0750_e40",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMBreasts_085e0750_e40.safetensors",
      "bytes": 310168344,
      "sha256": "039b6d5399def81c9a459d7cca8ccf749195fcb5f766f0899a387ba2fa6ad967"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmcumshot-v1.0-634c39cfcbfd9421a2d7b5adc62573fc232384c4c75e003c2e11d3408ad0765c",
    "adapterId": "hearmeman-hmcumshot",
    "publisher": "Hearmeman",
    "displayName": "HMCumshot_V1.0",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMCumshot_V1.0.safetensors",
      "bytes": 310168344,
      "sha256": "634c39cfcbfd9421a2d7b5adc62573fc232384c4c75e003c2e11d3408ad0765c"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmcumshot-v2-1a5b7948bb97f27737e62c3dd5497a3afb77517f230787f45e45c7d8fe3dc24d",
    "adapterId": "hearmeman-hmcumshot",
    "publisher": "Hearmeman",
    "displayName": "HMCumshot_V2",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMCumshot_V2.safetensors",
      "bytes": 626294968,
      "sha256": "1a5b7948bb97f27737e62c3dd5497a3afb77517f230787f45e45c7d8fe3dc24d"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [
      "hearmeman-hmcumshot-v1.0-634c39cfcbfd9421a2d7b5adc62573fc232384c4c75e003c2e11d3408ad0765c"
    ],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hminnie-v1-e50-499196c9d0e5f81ff575ba39a82987112c3bb1e09fbede858877cd950d6c8833",
    "adapterId": "hearmeman-hminnie-v1-e50",
    "publisher": "Hearmeman",
    "displayName": "HMInnie_v1_e50",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMInnie_v1_e50.safetensors",
      "bytes": 310168344,
      "sha256": "499196c9d0e5f81ff575ba39a82987112c3bb1e09fbede858877cd950d6c8833"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmmisdogv2-48e2a82f6bf0049dd42af11085c90bf08c6e2478f22072bebc7666daac2e2113",
    "adapterId": "hearmeman-hmmisdogv2",
    "publisher": "Hearmeman",
    "displayName": "HMMisDogV2",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMMisDogV2.safetensors",
      "bytes": 310168344,
      "sha256": "48e2a82f6bf0049dd42af11085c90bf08c6e2478f22072bebc7666daac2e2113"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmnsfw-aio-v2.5-a07732a84fd733085eb5d910f602f918fa7a3658117116927e4329f5951a9d2d",
    "adapterId": "hearmeman-hmnsfw-aio",
    "publisher": "Hearmeman",
    "displayName": "HMNSFW-AIO-V2.5",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMNSFW-AIO-V2.5.safetensors",
      "bytes": 86040232,
      "sha256": "a07732a84fd733085eb5d910f602f918fa7a3658117116927e4329f5951a9d2d"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [
      "hearmeman-hmnsfw-aio-v2-608e4212f2788b6063330ff1196fc1f4b4228cfd9a413a63c198a09d7e4a61cb"
    ],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmnsfw-aio-v2-608e4212f2788b6063330ff1196fc1f4b4228cfd9a413a63c198a09d7e4a61cb",
    "adapterId": "hearmeman-hmnsfw-aio",
    "publisher": "Hearmeman",
    "displayName": "HMNSFW_AIO_V2",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMNSFW_AIO_V2.safetensors",
      "bytes": 310168344,
      "sha256": "608e4212f2788b6063330ff1196fc1f4b4228cfd9a413a63c198a09d7e4a61cb"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmpenis-v2-e35-c6c58e9fee848b45e99f97d2520aba4ac63dfc354c07e13c29ac5d8a31a68060",
    "adapterId": "hearmeman-hmpenis-v2-e35",
    "publisher": "Hearmeman",
    "displayName": "HMPenis_v2_e35",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMPenis_v2_e35.safetensors",
      "bytes": 310168344,
      "sha256": "c6c58e9fee848b45e99f97d2520aba4ac63dfc354c07e13c29ac5d8a31a68060"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmsquirtv0.1-b25cc54db8e12012e9c1a60c514d767208c855cbf6e81605827d86913249cf24",
    "adapterId": "hearmeman-hmsquirtv0.1",
    "publisher": "Hearmeman",
    "displayName": "HMSquirtV0.1",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "HMSquirtV0.1.safetensors",
      "bytes": 86040232,
      "sha256": "b25cc54db8e12012e9c1a60c514d767208c855cbf6e81605827d86913249cf24"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-vagina-minimax-h3-epoch20-373c3cad3bf27047fdd754fe111443d97e70e3108a8829f2ec63c48832466eb3",
    "adapterId": "hearmeman-vagina-minimax-h3-epoch20",
    "publisher": "Hearmeman",
    "displayName": "Vagina_minimax-h3_epoch20",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "Vagina_minimax-h3_epoch20.safetensors",
      "bytes": 77580008,
      "sha256": "373c3cad3bf27047fdd754fe111443d97e70e3108a8829f2ec63c48832466eb3"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmmasturbation-v2-f0e4bfbe5baebe972880d2250a227e2f475aa8c18d6d01ed897288d9741659d2",
    "adapterId": "hearmeman-hmmasturbation-v2",
    "publisher": "Hearmeman",
    "displayName": "hmmasturbation_v2",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "hmmasturbation_v2.safetensors",
      "bytes": 310168344,
      "sha256": "f0e4bfbe5baebe972880d2250a227e2f475aa8c18d6d01ed897288d9741659d2"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-hmpussy-v6-epoch30-3080f4fbcbba4fc06bd09240c7eedb6a5128eb0e19feb001cdf97a7a0941a6ee",
    "adapterId": "hearmeman-hmpussy-v6-epoch30",
    "publisher": "Hearmeman",
    "displayName": "hmpussy_v6_epoch30",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "hmpussy_v6_epoch30.safetensors",
      "bytes": 626294968,
      "sha256": "3080f4fbcbba4fc06bd09240c7eedb6a5128eb0e19feb001cdf97a7a0941a6ee"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  },
  {
    "id": "hearmeman-vagassist-e40-2c2fdb66bf558de1aabda504a81d4ada5f4cebc20e8f519dc6ed3bb6d4be8c9a",
    "adapterId": "hearmeman-vagassist-e40",
    "publisher": "Hearmeman",
    "displayName": "vagassist_e40",
    "source": {
      "repository": "Hearmeman/minimax-h3-loras",
      "revision": "de4c3bc6122e68b88407c03dfecf521c803f098d",
      "file": "vagassist_e40.safetensors",
      "bytes": 310168344,
      "sha256": "2c2fdb66bf558de1aabda504a81d4ada5f4cebc20e8f519dc6ed3bb6d4be8c9a"
    },
    "license": {
      "name": "minimax-h3-community-license",
      "url": "https://huggingface.co/Hearmeman/minimax-h3-loras/blob/de4c3bc6122e68b88407c03dfecf521c803f098d/README.md"
    },
    "classification": "adult",
    "baseFamily": "minimax-h3",
    "availability": "current",
    "supersedes": [],
    "assessedAt": "2026-09-24T22:32:37.318Z",
    "compatibility": [
      {
        "recipeId": "comfyui-h3-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-video-768",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      },
      {
        "recipeId": "comfyui-h3-reference-video",
        "state": "unverified",
        "reason": "Adapter and recipe pairing has not completed Arke GPU validation."
      }
    ]
  }
].map(row => AdapterReleaseSchema.parse(row));
