import { ClientMessageSchema } from "@arke-studio/contracts";
/** Valid wire messages, shared by the live-gateway test and the real Chrome pairing check. */
export function hostOnlyCommandFixtures(sourcePath: string) {
    const worldId = "01ARZ3NDEKTSV4RRFFQ69G5FAV", conversationId = "cv_" + worldId;
    const playblast = { worldId, productionId: "pilot", sceneFile: "sc-one.md", sceneId: "sc_one", shotId: "sh_one",
      baseVersion: 1, stagingVersion: 1, durationSec: 1, aspect: "16:9", sourcePath, openingFrameSourcePath: sourcePath,
      referenceFrames: [{ kind: "last", at: 1, sourcePath }, { kind: "overview", at: 0, sourcePath }] };
    const hostCommands = [
      { kind: "file-artifact", worldId, sourcePath },
      { kind: "genesis-attach", genesisId: "new-world", sourcePath },
      { kind: "world-chat-attach", worldId, conversationId, sourcePath },
      { kind: "import-folder", worldId, sourcePath },
      { kind: "upload-artifacts", worldId, requestId: worldId, sourcePaths: [sourcePath] },
      { kind: "upload-artifacts", worldId, requestId: worldId },
      { kind: "stage-playblast", ...playblast },
      { kind: "conversation-action-stage-playblast-complete", ...playblast, conversationId, actionId: "act_" + worldId, status: "completed" },
    ];

    const payloads: Record<string, Record<string, unknown>> = {
      "account-open": { page: "account" }, "set-background-notifications": { preference: "off" },
      "set-credential": { provider: "openai", key: "test-secret-only" },
      "set-provider-plan": { provider: "google", plan: "free" },
      "clear-credential": { provider: "openai" },
      "submit-vendor-key": { vendor: "openai", key: "test-secret-only" },
      "begin-vendor-sign-in": { vendor: "openai", method: "oauth" },
      "submit-vendor-sign-in-code": { vendor: "openai", code: "test-code" },
      "remove-vendor-connection": { vendor: "openai", credential: "personal" },
      "sign-in-provider-tool": { provider: "higgsfield" },
      "cancel-provider-tool-sign-in": { provider: "higgsfield" },
      "select-provider-workspace": { provider: "higgsfield", workspaceId: null },
      "set-harness-engine": { engine: "claude" },
      "set-comfyui-url": { url: "http://127.0.0.1:8188" },
      "use-detected-comfyui": { location: "test-install" },
      "upload-world-image": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "upload-master-look": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "world-chat-attach-files": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","conversationId":"cv_01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "setup-skip": {"componentId":"kokoro-82m"},
      "setup-retry": {"componentId":"kokoro-82m"},
      "comfyui-update-runtime": {},
      "setup-pause": {"componentId":"kokoro-82m"},
      "setup-resume": {"componentId":"kokoro-82m"},
      "setup-repair": {"componentId":"kokoro-82m"},
      "setup-cancel": {},
      "cancel-vendor-sign-in": {},
      "choose-claude-executable": {},
      "clear-claude-executable": {},
      "choose-codex-executable": {},
      "clear-codex-executable": {},
      "choose-voxa-executable": {},
      "clear-voxa-executable": {},
      "use-bundled-voxa": {},
      "restart-voxa": {},
      "choose-comfyui-path": {},
      "choose-comfyui-models-dir": {},
      "clear-comfyui-models-dir": {},
      "clear-comfyui-engine": {},
      "comfyui-restart": {},
      "setup-install": {"componentId":"kokoro-82m"},
      "setup-remove": {"componentId":"kokoro-82m"},
      "repair-voice-models": {},
      "open-model-folder": {},
      "open-engine-log": {"engine":"voxa"},
      "account-sign-in": {},
      "account-create": {},
      "account-cancel-sign-in": {},
      "account-sign-out": {},
      "import-location-view-candidate": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","sheetId":"maren-kest"},
      "import-prop-state-candidate": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","propId":"prop_01ARZ3NDEKTSV4RRFFQ69G5FAV","stateId":"pst_01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "import-main-photo-candidate": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","sheetId":"maren-kest"},
      "import-main-photo": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","sheetId":"maren-kest"},
      "import-character-sheet": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","sheetId":"maren-kest"},
      "import-shot-frame": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","productionId":"pilot","shotId":"sh_1","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "attach-files": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "genesis-attach-files": {"genesisId":"new-world"},
      "stage-audiobook-take": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","productionId":"pilot","chapterFile":"01-neap.md","block":"p0.0","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "stage-audiobook-lines": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","productionId":"pilot","speaker":"narrator","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "probe-grouped-read": {"requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","productionId":"pilot","chapterFile":"01-neap.md"},
      "open-exports-folder": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "pick-manuscript": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","productionId":"pilot","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "download-update": {},
      "install-update-and-restart": {},
      "install-update-on-close": {},
      "generate-diagnostics": {},
      "probe-grouped-read": {"requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","productionId":"pilot","chapterFile":"01-neap.md"},
      "open-data-folder": {},
      "bench-upload-references": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","sessionId":"sess_01ARZ3NDEKTSV4RRFFQ69G5FAV","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "attach-files-correlated": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV"},
      "pick-staged-reference": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","key":"world-image"},
      "adapter-command": {"command":{"action":"install","releaseIds":["test-adapter"]}},
      "stage-voice-clip": {"worldId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","requestId":"01ARZ3NDEKTSV4RRFFQ69G5FAV","source":{"from":"chosen"}},
    };
    return [...hostCommands, ...Object.entries(payloads).map(([kind, payload]) => ({ kind, ...payload })), { kind: "adapter-command", command: { action: "remove", releaseId: "test-adapter", deleteOwnedFile: true } }].map(command => ClientMessageSchema.parse(command));
}
