import type { WorldChatPreparedAction } from "./world-chat-actions.js";
import type { ClientMessage } from "./frames.js";
import type { AdapterAction } from "./adapters.js";

/** Every wire command must make an explicit remote-ownership choice (turn 175, #1373).
 * Studio operations act on world content or preferences; host operations own native UI,
 * credentials, installation or machine processes. Payload cases mix both and are checked below. */
export const REMOTE_COMMAND_ACCESS = {
  // host
  "upload-world-image": "host", "upload-master-look": "host", "world-chat-attach": "host",
  "world-chat-attach-files": "host", "setup-skip": "host", "setup-retry": "host",
  "comfyui-update-runtime": "host", "setup-pause": "host", "setup-resume": "host",
  "setup-repair": "host", "setup-cancel": "host", "set-credential": "host", "set-provider-plan": "host",
  "clear-credential": "host", "sign-in-provider-tool": "host", "cancel-provider-tool-sign-in": "host",
  "select-provider-workspace": "host", "begin-vendor-sign-in": "host", "submit-vendor-sign-in-code": "host",
  "submit-vendor-key": "host", "cancel-vendor-sign-in": "host", "remove-vendor-connection": "host",
  "set-harness-engine": "host", "choose-claude-executable": "host", "clear-claude-executable": "host",
  "choose-codex-executable": "host", "clear-codex-executable": "host", "choose-voxa-executable": "host",
  "clear-voxa-executable": "host", "use-bundled-voxa": "host", "restart-voxa": "host",
  "choose-comfyui-path": "host", "choose-comfyui-models-dir": "host", "clear-comfyui-models-dir": "host",
  "set-comfyui-url": "host", "clear-comfyui-engine": "host", "use-detected-comfyui": "host",
  "comfyui-restart": "host", "setup-install": "host", "setup-remove": "host",
  "repair-voice-models": "host", "open-model-folder": "host", "open-engine-log": "host",
  "set-background-notifications": "host", "account-sign-in": "host", "account-create": "host",
  "account-cancel-sign-in": "host", "account-sign-out": "host", "account-open": "host",
  "import-location-view-candidate": "host", "import-prop-state-candidate": "host", "import-main-photo-candidate": "host",
  "import-main-photo": "host", "import-character-sheet": "host", "import-shot-frame": "host",
  "stage-playblast": "host", "conversation-action-stage-playblast-complete": "host", "upload-artifacts": "host",
  "file-artifact": "host", "attach-files": "host", "genesis-attach": "host",
  "genesis-attach-files": "host", "import-folder": "host", "stage-audiobook-take": "host",
  "stage-audiobook-lines": "host", "open-exports-folder": "host", "pick-manuscript": "host",
  "download-update": "host", "install-update-and-restart": "host", "install-update-on-close": "host",
  "generate-diagnostics": "host", "probe-grouped-read": "host", "open-data-folder": "host", "bench-upload-references": "host",
  "attach-files-correlated": "host",
  // payload
  "pick-staged-reference": "payload", "adapter-command": "payload", "stage-voice-clip": "payload",
  // studio
  "catalogue-voice-preview": "studio", "stop-catalogue-voice-preview": "studio",
  "production-setup": "studio", "save-production-narrative": "studio", "stage-construct": "studio",
  "stage-inspection": "studio", "stage-construct-cancel": "studio", "stage-review-discard": "studio", "hello": "studio",
  "open-world": "studio", "create-world": "studio", "read-sheet-section": "studio",
  "read-sheet-page": "studio", "read-prose": "studio", "read-prose-page": "studio",
  "stop-prose-page": "studio", "read-bible-section": "studio", "generate-world-image": "studio",
  "use-world-image": "studio", "discard-world-image": "studio", "generate-master-look": "studio",
  "browse-reference-images": "studio", "clear-staged-reference": "studio", "use-master-look": "studio",
  "discard-master-look": "studio", "archive-world": "studio", "install-sample-world": "studio",
  "reconcile-external-edit": "studio", "stage-sheet-edit": "studio", "restore-sheet-version": "studio",
  "stage-art-direction-change": "studio", "set-art-direction": "studio", "proposal-accept": "studio",
  "proposal-discard": "studio", "proposal-rebase": "studio", "proposal-resolve-conflict": "studio",
  "proposal-mark-seen": "studio", "proposal-resolve-choice": "studio", "proposal-update-field": "studio",
  "proposal-update-passage": "studio", "world-chat-open": "studio", "conversation-action-decide": "resolved",
  "world-chat-send": "studio", "world-chat-send-status": "studio", "world-chat-wrap-up": "studio",
  "world-chat-save-point": "studio", "world-chat-reject-point": "studio", "world-chat-open-media": "studio",
  "world-chat-retry-turn": "studio", "proposal-send-back": "studio", "world-chat-cancel": "studio",
  "world-chat-create": "studio", "world-chat-delete": "studio", "world-chat-set-initiative": "studio",
  "world-chat-archive": "studio", "world-chat-unarchive": "studio", "world-chat-upload": "studio",
  "world-chat-promote-attachment": "studio", "draft-with-studio": "studio", "authoring-cancel": "studio",
  "genesis-chat": "studio", "genesis-discard": "studio", "genesis-list": "studio",
  "genesis-load": "studio", "genesis-review": "studio", "genesis-images": "studio",
  "genesis-voices": "studio", "genesis-readiness": "studio", "genesis-readiness-leave": "studio",
  "genesis-voice-generate": "studio", "genesis-voice-decide": "studio", "genesis-imports": "studio",
  "genesis-import-resolve": "studio", "genesis-image-generate": "studio", "genesis-image-decide": "studio",
  "genesis-propose-world": "studio", "genesis-decide": "studio", "plan-founding-build": "studio",
  "begin-founding-build": "studio", "stop-founding-build": "studio", "plan-key-art": "studio",
  "cancel-key-art-prompt": "studio", "generate-look-preview": "studio", "run-build-item": "studio",
  "dismiss-build-notice": "studio", "permission-reply": "studio", "canon-ask": "studio",
  "canon-search": "studio", "canon-refs": "studio", "stage-canon-entry": "studio",
  "stage-canon-amendment": "studio", "open-thread": "studio", "settle-thread": "studio",
  "retire-entity": "studio", "undo-single-act": "studio", "canon-contradictions": "studio",
  "create-sheet-from-sentence": "studio", "promote-guest": "studio", "duplicate-sheet": "studio",
  "set-sheet-status": "studio", "rename-world": "studio", "rename-sheet": "studio",
  "assign-voice": "studio", "sheet-refs": "studio", "validate-provider": "studio",
  "refresh-provider-tool": "studio", "refresh-vendor-auth": "studio", "set-routing-default": "studio",
  "set-model-enabled": "studio", "set-research-web": "studio", "set-local-sampling": "studio", "set-agent-config": "studio",
  "list-harness-models": "studio", "set-spend-threshold": "studio", "detect-runtimes": "studio",
  "detect-harnesses": "studio", "comfyui-refresh": "studio", "comfyui-verify-recipe": "studio",
  "test-local-voice": "studio", "mark-inbox-seen": "studio", "mark-whats-new-seen": "studio",
  "set-appearance-theme": "studio", "set-narrator": "studio", "cancel-job": "studio",
  "list-provider-calls": "studio", "retry-job-finalization": "studio", "delete-job": "studio",
  "resolve-held-job": "studio", "queue-resume": "studio", "establish-look": "studio",
  "choose-anchor": "studio", "generate-location-view": "studio", "accept-location-view": "studio",
  "create-prop": "studio", "add-prop-state": "studio", "accept-prop-state": "studio",
  "generate-main-photo": "studio", "convert-performance": "studio", "record-dialogue-feedback": "studio",
  "propose-shot-visual-facts": "studio", "plan-table-read": "studio", "prepare-table-read": "studio",
  "save-rehearsal-note": "studio", "designate-performance-bible": "studio", "clear-performance-bible": "studio",
  "prepare-performance-generation": "studio", "generate-performance": "studio", "cancel-performance-generation": "studio",
  "propose-performance-duration": "studio", "place-selected-performance": "studio", "clear-performance-selection": "studio",
  "review-performance": "studio", "purge-performance": "studio", "keep-performance-recording": "studio",
  "resume-character-voice-sample": "studio", "prepare-character-voice-sample": "studio", "accept-character-voice-sample": "studio",
  "clear-character-voice-sample": "studio", "withdraw-character-voice-sample": "studio", "generate-character-voice-sample": "studio",
  "generate-character-sheet": "studio", "accept-character-sheet": "studio", "generate-character-looks": "studio",
  "accept-character-look": "studio", "reject-reference-take": "studio", "promote-character-look": "studio",
  "attach-character-look": "studio", "lock-tile": "studio", "generate-missing-tiles": "studio",
  "regenerate-tile": "studio", "compile-grid": "studio", "designate-compilation": "studio",
  "set-style-override": "studio", "voice-candidates": "studio", "voice-catalogue": "studio",
  "voice-line": "studio", "voice-preview": "studio", "transcribe-dictation": "studio",
  "design-voice": "studio", "save-designed-voice": "studio", "hear-designed-voice": "studio",
  "create-production": "studio", "propose-story-overview": "studio", "draft-story-overview": "studio",
  "propose-season": "studio", "create-episode": "studio", "propose-episode": "studio",
  "reorder-episodes": "studio", "draft-scene": "studio", "create-scene": "studio",
  "restore-scene": "studio", "delete-scene": "studio", "scene-command": "studio",
  "create-chapter": "studio", "open-chapter": "studio", "save-chapter": "studio",
  "retire-chapter": "studio", "restore-chapter-retired": "studio", "edit-chapter-plan": "studio",
  "restore-chapter": "studio", "save-bible": "studio", "restore-bible": "studio",
  "reorder-chapters": "studio", "reorder-scenes": "studio", "set-production-aspect": "studio",
  "set-world-model": "studio", "set-world-image-inspection": "studio", "set-image-inspection": "studio", "set-production-model": "studio", "frame-run-quote": "studio",
  "frame-run-start": "studio", "frame-run-pause": "studio", "frame-run-resume": "studio",
  "frame-run-cancel": "studio", "frame-run-retry-step": "studio", "frame-run-retry-cell": "studio",
  "frame-run-list": "studio", "frame-run-dismiss": "studio", "prepare-master-audio-reference": "studio",
  "prepare-performance-audio-reference": "studio", "dispatch-scene-planned": "studio", "plan-continue": "studio",
  "plan-reconfirm": "studio", "plan-cancel": "studio", "list-plans": "studio",
  "save-routing": "studio", "routing-command": "studio", "record-traversal": "studio",
  "list-routing-findings": "studio", "propose-branch-canon": "studio", "export-interactive": "studio",
  "compile-scene-board": "studio", "export-scene-board": "studio", "dispatch-scene": "studio",
  "record-review": "studio", "accept-take": "studio", "clear-shot-frame": "studio",
  "reject-take": "studio", "set-trim": "studio", "timeline-move-picture": "studio",
  "timeline-command": "studio", "editor-request-decide": "studio", "timeline-history": "studio",
  "save-audio-tracks": "studio", "browse-world-artifacts": "studio", "borrow-artifacts": "studio",
  "place-overlay": "studio", "move-overlay": "studio", "split-overlay-audio": "studio",
  "rejoin-overlay-audio": "studio", "remove-overlay": "studio", "export-cut": "studio",
  "timeline-transcribe": "studio", "timeline-assemble": "studio", "cancel-export": "studio",
  "export-world": "studio", "retire-artifact": "studio", "restore-artifact": "studio",
  "clone-voice": "studio", "discard-voice-clip": "studio", "delete-voice": "studio",
  "extract-artifact": "studio", "stop-extraction": "studio", "derive-continuity": "studio",
  "stop-continuity": "studio", "cast-voices": "studio", "stop-voices": "studio",
  "set-voice-pin": "studio", "read-audiobook-chapter": "studio", "stop-audiobook": "studio",
  "set-audiobook-reading": "studio", "set-audiobook-recorded": "studio", "set-audiobook-note": "studio",
  "set-audiobook-narrator": "studio", "quote-audiobook-narrator": "studio", "hear-audiobook-line": "studio",
  "set-audiobook-requests": "studio", "keep-audiobook-split": "studio",
  "keep-audiobook-take": "studio", "discard-audiobook-take": "studio", "export-audiobook-script": "studio",
  "preview-audiobook-script": "studio", "keep-audiobook-lines": "studio", "discard-audiobook-lines": "studio", "set-audiobook-block": "studio",
  "direct-chapter": "studio", "open-audiobook": "studio", "open-audiobook-listening": "studio", "set-audiobook-picture": "studio", "derive-audiobook-look": "studio", "set-audiobook-look": "studio", "choose-audiobook-look": "studio", "read-audiobook-looks": "studio", "suggest-audiobook-picture": "studio", "make-audiobook-picture": "studio", "illustrate-chapter": "studio", "discard-illustration": "studio", "accept-illustration": "studio", "stop-illustration": "studio", "set-audiobook-timing": "studio", "set-audiobook-reaction": "studio", "set-audiobook-bed": "studio", "set-audiobook-sound": "studio", "propose-audiobook-timing": "studio", "accept-audiobook-timing": "studio", "render-audiobook-mix": "studio", "export-audiobook-player": "studio", "list-web-packages": "studio", "read-audiobook-book": "studio",
  "stop-audiobook-book": "studio", "discard-direction": "studio", "accept-direction": "studio",
  "preview-direction": "studio", "set-audiobook-reading-note": "studio", "draft-audiobook-speaker-notes": "studio",
  "export-manuscript": "studio", "import-manuscript": "studio", "reread-manuscript": "studio",
  "cancel-manuscript": "studio", "resolve-extraction": "studio", "check-updates": "studio",
  "acknowledge-update": "studio", "refresh-diagnostics": "studio", "bench-open": "studio",
  "bench-open-subject": "studio", "bench-rebuild-subject": "studio", "bench-new-session": "studio",
  "bench-close": "studio", "bench-set-title": "studio", "bench-compose": "studio",
  "bench-add-reference": "studio", "bench-remove-reference": "studio", "bench-enhance-brief": "studio",
  "bible-helper-run": "studio", "bench-draft-lyrics": "studio", "bench-preset-save": "studio",
  "bench-preset-delete": "studio", "bench-dispatch": "studio", "bench-rerun": "studio",
  "bench-keep": "studio", "bench-accept": "studio", "bench-discard": "studio",
  "bench-clear-view": "studio", "bench-take-files": "studio", "bench-delete": "studio", "bench-upscale": "studio", "bench-select-take": "studio", "stage-artifact-reference": "studio",
} as const satisfies Record<ClientMessage["kind"], "host" | "payload" | "resolved" | "studio">;

export type RemoteHostCommand = { [K in keyof typeof REMOTE_COMMAND_ACCESS]: typeof REMOTE_COMMAND_ACCESS[K] extends "host" | "payload" ? K : never }[keyof typeof REMOTE_COMMAND_ACCESS];

const adapterAccess = { refresh: "studio", enable: "studio", "disable-content": "studio",
  install: "host", disable: "studio", restore: "studio", remove: "payload" } as const satisfies Record<AdapterAction["action"], "host" | "payload" | "studio">;

/** Recorded bytes and existing world references never open the PC file chooser. */
export function isRemoteHostCommand(message: ClientMessage): boolean {
  // The gateway adds a restriction and the lifecycle checks the stored card, including replays.
  if (message.kind === "conversation-action-decide") return false;
  if (message.kind === "stage-voice-clip") return message.source?.from !== "recorded";
  if (message.kind === "pick-staged-reference") return message.worldFile === undefined && message.image === undefined;
  if (message.kind === "adapter-command") return message.command?.action === "remove" ? message.command.deleteOwnedFile : adapterAccess[message.command?.action] !== "studio";
  return REMOTE_COMMAND_ACCESS[message.kind] !== "studio";
}

/** Conversation decisions resolve these prepared kinds from the durable card, never from the browser. */
export const REMOTE_PREPARED_ACTION_ACCESS = {
  "world-chat-prop-authoring": "studio", "world-chat-prop-reference": "studio",
  "world-chat-proposal": "studio", "world-chat-bible-edit": "studio",
  "world-chat-scene-edit": "studio", "world-chat-editor-request": "studio",
  "world-chat-world-metadata": "studio", "world-chat-canon": "studio",
  "world-chat-canon-retire": "studio", "world-chat-canon-restore": "studio",
  "world-chat-sheet": "studio", "world-chat-sheet-retire": "studio",
  "world-chat-sheet-restore": "studio", "world-chat-art-direction": "studio",
  "world-chat-art-direction-restore": "studio", "world-chat-artifact-import": "host",
  "world-chat-artifact-metadata": "studio", "world-chat-artifact-extraction": "studio",
  "world-chat-artifact-extraction-stop": "studio", "world-chat-artifact-extraction-review": "studio",
  "world-chat-artifact-reference": "studio", "world-chat-reference-import": "host",
  "world-chat-reference-result-use": "studio", "world-chat-reference-review": "studio",
  "world-chat-reference-change": "studio", "world-chat-reference-tile-lock": "studio",
  "world-chat-reference-compile": "studio", "world-chat-reference-style": "studio",
  "world-chat-reference-generation": "studio", "world-chat-reference-image-import": "host",
  "world-chat-reference-world-image-result-use": "studio", "world-chat-reference-master-look-result-use": "studio",
  "world-chat-reference-image-discard": "studio", "world-chat-voice-assignment": "studio",
  "world-chat-voice-audition": "studio", "world-chat-voice-clone": "host",
  "world-chat-voice-clip-review": "studio", "world-chat-world-archive": "studio",
  "world-chat-world-export": "studio", "world-chat-production-create": "studio",
  "world-chat-production-metadata": "studio", "world-chat-production-model": "studio",
  "world-chat-production-series": "studio", "world-chat-production-overview": "studio",
  "world-chat-production-prose-style": "studio", "world-chat-production-season": "studio",
  "world-chat-production-episode": "studio", "world-chat-production-chapter": "studio",
  "world-chat-production-scene": "studio", "world-chat-production-episode-order": "studio",
  "world-chat-production-chapter-order": "studio", "world-chat-production-scene-order": "studio",
  "world-chat-production-scene-delete": "studio", "world-chat-production-scene-restore": "studio",
  "world-chat-production-style": "studio", "world-chat-production-scene-command": "studio",
  "world-chat-production-board-compile": "studio", "world-chat-production-board-export": "studio",
  "world-chat-production-take-import": "host", "world-chat-production-take-generation": "studio",
  "world-chat-production-frame-run-start": "studio",
  "world-chat-production-frame-run-pause": "studio",
  "world-chat-production-frame-run-resume": "studio",
  "world-chat-production-frame-run-cancel": "studio",
  "world-chat-production-frame-run-retry-step": "studio",
  "world-chat-production-frame-run-retry-cell": "studio",
  "world-chat-production-scene-dispatch": "studio",
  "world-chat-production-plan-cancel": "studio",
  "world-chat-production-take-review": "studio", "world-chat-production-take-trim": "studio",
  "world-chat-production-take-file": "studio", "world-chat-production-shot-frame-clear": "studio",
  "world-chat-production-stage-playblast": "host", "world-chat-production-stage-construct": "studio",
  "world-chat-audio-spine-command": "studio", "world-chat-production-routing": "studio",
  "world-chat-production-routing-traversal": "studio", "world-chat-production-branch-canon": "studio",
  "world-chat-production-interactive-export": "studio", "world-chat-production-cut-export": "studio",
  "world-chat-production-export-cancel": "studio", "world-chat-bench-generation": "studio",
  "world-chat-bench-keep": "studio", "world-chat-bench-select": "studio", "world-chat-bench-discard": "studio",
  "world-chat-image-generation": "studio", "world-chat-build-item-run": "studio",
} as const satisfies Record<WorldChatPreparedAction["kind"], "host" | "studio">;

export function isRemoteHostConversationAction(kind: string): boolean {
  const access = (REMOTE_PREPARED_ACTION_ACCESS as Readonly<Record<string, string>>)[kind]
    ?? (REMOTE_COMMAND_ACCESS as Readonly<Record<string, string>>)[kind];
  return access !== "studio";
}
