// Generated by packages/providers/scripts/sync-fal-catalogue.mjs — do not edit by hand.
// Route ids and prices come from https://fal.ai/api/models (public, no key). What a model
// accepts is curated in that script, because the API does not say.
// Catalogue size at generation: 1464 models. Regenerate when fal ships something worth having.

import type { ManifestModel } from "@arke-studio/contracts";

export const FAL_MODELS: readonly ManifestModel[] = [
  {
    "id": "flux-2-pro",
    "provider": "fal",
    "capability": "image",
    "displayName": "Flux 2 Pro",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "resolutions": [
        "1MP",
        "2MP",
        "4MP"
      ],
      "tiers": {
        "1K": "1MP",
        "2K": "2MP",
        "4K": "4MP"
      },
      "aspects": [
        "16:9",
        "9:16",
        "1:1",
        "4:3"
      ]
    },
    "pricing": {
      "kind": "perMegapixel",
      "microUsdPerMegapixel": 30000
    }
  },
  {
    "id": "nano-banana-2",
    "provider": "fal",
    "capability": "image",
    "displayName": "Nano Banana 2",
    "accepts": {
      "referenceImages": 3,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 50000,
      "resolutions": [
        "1K",
        "2K",
        "4K"
      ],
      "tiers": {
        "1K": "1K",
        "2K": "2K",
        "4K": "4K"
      },
      "aspects": [
        "21:9",
        "16:9",
        "3:2",
        "4:3",
        "1:1",
        "4:5",
        "3:4",
        "2:3",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perImage",
      "microUsdPerImage": 80000
    }
  },
  {
    "id": "nano-banana-pro",
    "provider": "fal",
    "capability": "image",
    "displayName": "Nano Banana Pro",
    "accepts": {
      "referenceImages": 3,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 50000,
      "resolutions": [
        "1K",
        "2K",
        "4K"
      ],
      "tiers": {
        "1K": "1K",
        "2K": "2K",
        "4K": "4K"
      },
      "aspects": [
        "21:9",
        "16:9",
        "3:2",
        "4:3",
        "1:1",
        "4:5",
        "3:4",
        "2:3",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perImage",
      "microUsdPerImage": 150000
    }
  },
  {
    "id": "gpt-image-2-fal",
    "provider": "fal",
    "capability": "image",
    "displayName": "GPT Image 2",
    "accepts": {
      "referenceImages": 16,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 32000,
      "aspects": [
        "16:9",
        "3:2",
        "1:1",
        "2:3",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perImageToken",
      "microUsdPerMillionTextInput": 5000000,
      "microUsdPerMillionImageInput": 8000000,
      "microUsdPerMillionImageOutput": 30000000,
      "assumedTextInputTokens": 500,
      "assumedImageInputTokensPerReference": 1500,
      "assumedImageOutputTokensPerImage": 6500,
      "roundUpToMicroUsd": 100
    }
  },
  {
    "id": "seedance-2.0",
    "provider": "fal",
    "capability": "video",
    "displayName": "Seedance 2.0 Text to Video API",
    "accepts": {
      "referenceImages": 9,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxReferenceVideoSec": 15,
      "maxReferenceAudioSec": 15,
      "referencesField": "image_urls",
      "soundChoice": true,
      "durationAuto": true,
      "maxDurationSec": 15,
      "durations": {
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
        "14": "14",
        "15": "15"
      },
      "resolutions": [
        "720p",
        "1080p"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1"
      ],
      "storyboardPanels": 15
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 303400,
      "byResolution": {
        "1080p": 682000
      }
    },
    "family": "seedance",
    "modes": {
      "generate": {
        "locked": []
      },
      "first-frame": {
        "route": "bytedance/seedance-2.0/image-to-video",
        "locked": [
          "aspect"
        ]
      },
      "first-and-last-frame": {
        "route": "bytedance/seedance-2.0/image-to-video",
        "locked": [
          "aspect"
        ]
      }
    }
  },
  {
    "id": "seedance-2.0-fast",
    "provider": "fal",
    "capability": "video",
    "displayName": "Seedance 2.0 Fast Text to Video",
    "accepts": {
      "referenceImages": 9,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxReferenceVideoSec": 15,
      "maxReferenceAudioSec": 15,
      "referencesField": "image_urls",
      "soundChoice": true,
      "durationAuto": true,
      "maxDurationSec": 15,
      "durations": {
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
        "14": "14",
        "15": "15"
      },
      "resolutions": [
        "720p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ],
      "storyboardPanels": 15
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 241900
    },
    "family": "seedance",
    "modes": {
      "generate": {
        "locked": []
      },
      "first-frame": {
        "route": "bytedance/seedance-2.0/fast/image-to-video",
        "locked": [
          "aspect"
        ]
      },
      "first-and-last-frame": {
        "route": "bytedance/seedance-2.0/fast/image-to-video",
        "locked": [
          "aspect"
        ]
      }
    }
  },
  {
    "id": "veo-3.1",
    "provider": "fal",
    "capability": "video",
    "displayName": "Veo 3.1",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 20000,
      "soundChoice": true,
      "maxDurationSec": 8,
      "durations": {
        "4": "4s",
        "6": "6s",
        "8": "8s"
      },
      "resolutions": [
        "720p",
        "1080p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 200000
    }
  },
  {
    "id": "veo-3.1-fast",
    "provider": "fal",
    "capability": "video",
    "displayName": "Veo 3.1 Fast",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 20000,
      "soundChoice": true,
      "maxDurationSec": 8,
      "durations": {
        "4": "4s",
        "6": "6s",
        "8": "8s"
      },
      "resolutions": [
        "720p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 100000
    }
  },
  {
    "id": "minimax-h3",
    "provider": "fal",
    "capability": "video",
    "displayName": "MiniMax H3",
    "accepts": {
      "referenceImages": 9,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 50000,
      "maxReferenceVideoSec": 15,
      "maxReferenceAudioSec": 15,
      "referencesField": "reference_image_urls",
      "maxDurationSec": 15,
      "durationWire": "number",
      "durations": {
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
        "14": "14",
        "15": "15"
      },
      "resolutions": [
        "2K",
        "480P",
        "768P",
        "4K"
      ],
      "aspects": [
        "21:9",
        "16:9",
        "4:3",
        "1:1",
        "3:4",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 130000,
      "byResolution": {
        "480P": 50000,
        "768P": 60000,
        "2K": 130000,
        "4K": 160000
      }
    },
    "family": "minimax-h3",
    "modes": {
      "generate": {
        "locked": []
      },
      "first-frame": {
        "route": "minimax/h3/image-to-video",
        "locked": [
          "aspect"
        ]
      },
      "first-and-last-frame": {
        "route": "minimax/h3/image-to-video",
        "locked": [
          "aspect"
        ]
      }
    }
  },
  {
    "id": "ltx-2.5-pro",
    "provider": "fal",
    "capability": "video",
    "displayName": "LTX 2.5 Pro",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 5000,
      "soundChoice": true,
      "durationAuto": true,
      "maxDurationSec": 10,
      "durationWire": "number",
      "durations": {
        "6": "6",
        "8": "8",
        "10": "10"
      },
      "resolutions": [
        "1080p",
        "720p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 170000,
      "byResolution": {
        "720p": 120000,
        "1080p": 170000
      }
    },
    "family": "ltx",
    "modes": {
      "generate": {
        "locked": []
      },
      "first-frame": {
        "route": "lightricks/ltx-2.5/image-to-video/pro",
        "locked": []
      },
      "first-and-last-frame": {
        "route": "lightricks/ltx-2.5/image-to-video/pro",
        "locked": []
      }
    }
  },
  {
    "id": "ltx-2.5-fast",
    "provider": "fal",
    "capability": "video",
    "displayName": "LTX 2.5 Fast",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 5000,
      "soundChoice": true,
      "durationAuto": true,
      "maxDurationSec": 20,
      "durationWire": "number",
      "durations": {
        "6": "6",
        "8": "8",
        "10": "10",
        "12": "12",
        "14": "14",
        "16": "16",
        "18": "18",
        "20": "20"
      },
      "resolutions": [
        "1080p",
        "720p",
        "1440p",
        "2160p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 130000,
      "byResolution": {
        "720p": 90000,
        "1080p": 130000,
        "1440p": 190000,
        "2160p": 300000
      }
    },
    "family": "ltx",
    "modes": {
      "generate": {
        "locked": []
      },
      "first-frame": {
        "route": "lightricks/ltx-2.5/image-to-video/fast",
        "locked": []
      },
      "first-and-last-frame": {
        "route": "lightricks/ltx-2.5/image-to-video/fast",
        "locked": []
      }
    }
  },
  {
    "id": "wan-2.7",
    "provider": "fal",
    "capability": "video",
    "displayName": "Wan 2.7",
    "accepts": {
      "referenceImages": 4,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "referencesField": "reference_image_urls",
      "maxReferenceDurationSec": 10,
      "maxDurationSec": 15,
      "durationWire": "number",
      "durations": {
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
        "14": "14",
        "15": "15"
      },
      "resolutions": [
        "1080p",
        "720p"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1",
        "4:3",
        "3:4"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 150000,
      "byResolution": {
        "1080p": 150000,
        "720p": 100000
      }
    },
    "family": "wan",
    "modes": {
      "generate": {
        "locked": []
      },
      "first-frame": {
        "route": "fal-ai/wan/v2.7/image-to-video",
        "locked": [
          "aspect"
        ]
      },
      "first-and-last-frame": {
        "route": "fal-ai/wan/v2.7/image-to-video",
        "locked": [
          "aspect"
        ]
      }
    }
  },
  {
    "id": "kling-3-pro",
    "provider": "fal",
    "capability": "video",
    "displayName": "Kling Video v3 Text to Video [Pro]",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 2500,
      "soundChoice": true,
      "maxDurationSec": 15,
      "durations": {
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
        "14": "14",
        "15": "15"
      },
      "aspects": [
        "16:9",
        "9:16",
        "1:1"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 112000
    }
  },
  {
    "id": "kling-3-standard",
    "provider": "fal",
    "capability": "video",
    "displayName": "Kling Video v3 Text to Video [Standard]",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "maxPromptChars": 2500,
      "soundChoice": true,
      "maxDurationSec": 15,
      "durations": {
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
        "14": "14",
        "15": "15"
      },
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 84000
    }
  }
] as const;

/** Model id → fal route. Dispatch needs this; a model without one cannot be submitted. */
export const FAL_ENDPOINTS: Record<string, string> = {
  "flux-2-pro": "fal-ai/flux-2-pro",
  "nano-banana-2": "fal-ai/nano-banana-2",
  "nano-banana-pro": "fal-ai/nano-banana-pro",
  "gpt-image-2-fal": "openai/gpt-image-2",
  "seedance-2.0": "bytedance/seedance-2.0/text-to-video",
  "seedance-2.0-fast": "bytedance/seedance-2.0/fast/text-to-video",
  "veo-3.1": "fal-ai/veo3.1",
  "veo-3.1-fast": "fal-ai/veo3.1/fast",
  "minimax-h3": "minimax/h3/text-to-video",
  "ltx-2.5-pro": "lightricks/ltx-2.5/text-to-video/pro",
  "ltx-2.5-fast": "lightricks/ltx-2.5/text-to-video/fast",
  "wan-2.7": "fal-ai/wan/v2.7/text-to-video",
  "kling-3-pro": "fal-ai/kling-video/v3/pro/text-to-video",
  "kling-3-standard": "fal-ai/kling-video/v3/standard/text-to-video"
};

/**
 * Model id → the route that accepts reference images. Present only for models whose manifest
 * row declares `accepts.referenceImages > 0`; a job carrying references submits here instead
 * of the text route above.
 */
export const FAL_EDIT_ENDPOINTS: Record<string, string> = {
  "nano-banana-2": "fal-ai/nano-banana-2/edit",
  "nano-banana-pro": "fal-ai/nano-banana-pro/edit",
  "gpt-image-2-fal": "openai/gpt-image-2/edit",
  "seedance-2.0": "bytedance/seedance-2.0/reference-to-video",
  "seedance-2.0-fast": "bytedance/seedance-2.0/fast/reference-to-video",
  "minimax-h3": "minimax/h3/reference-to-video",
  "wan-2.7": "fal-ai/wan/v2.7/reference-to-video"
};
