// Generated by packages/providers/scripts/sync-fal-catalogue.mjs — do not edit by hand.
// Route ids and prices come from https://fal.ai/api/models (public, no key). What a model
// accepts is curated in that script, because the API does not say.
// Catalogue size at generation: 1404 models. Regenerate when fal ships something worth having.

import type { ManifestModel } from "@arke-studio/contracts";

export const FAL_MODELS: readonly ManifestModel[] = [
  {
    "id": "flux-2-pro",
    "provider": "fal",
    "capability": "image",
    "displayName": "Flux 2 Pro",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "resolutions": [
        "1MP",
        "2MP",
        "4MP"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1",
        "4:3"
      ]
    },
    "pricing": {
      "kind": "perMegapixel",
      "microUsdPerMegapixel": 30000
    }
  },
  {
    "id": "nano-banana-2",
    "provider": "fal",
    "capability": "image",
    "displayName": "Nano Banana 2",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "resolutions": [
        "1K",
        "2K",
        "4K"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1"
      ]
    },
    "pricing": {
      "kind": "perImage",
      "microUsdPerImage": 80000
    }
  },
  {
    "id": "nano-banana-pro",
    "provider": "fal",
    "capability": "image",
    "displayName": "Nano Banana Pro",
    "accepts": {
      "referenceImages": 0,
      "startFrame": false,
      "endFrame": false
    },
    "limits": {
      "resolutions": [
        "1K",
        "2K",
        "4K"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1"
      ]
    },
    "pricing": {
      "kind": "perImage",
      "microUsdPerImage": 150000
    }
  },
  {
    "id": "seedance-2.0",
    "provider": "fal",
    "capability": "video",
    "displayName": "Seedance 2.0 Text to Video API",
    "accepts": {
      "referenceImages": 0,
      "startFrame": true,
      "endFrame": true
    },
    "limits": {
      "maxDurationSec": 15,
      "resolutions": [
        "720p",
        "1080p"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 303400,
      "byResolution": {
        "1080p": 682000
      }
    }
  },
  {
    "id": "seedance-2.0-fast",
    "provider": "fal",
    "capability": "video",
    "displayName": "Seedance 2.0 Fast Text to Video",
    "accepts": {
      "referenceImages": 0,
      "startFrame": true,
      "endFrame": true
    },
    "limits": {
      "maxDurationSec": 15,
      "resolutions": [
        "720p",
        "1080p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 241900
    }
  },
  {
    "id": "veo-3.1",
    "provider": "fal",
    "capability": "video",
    "displayName": "Veo 3.1",
    "accepts": {
      "referenceImages": 0,
      "startFrame": true,
      "endFrame": true
    },
    "limits": {
      "maxDurationSec": 8,
      "resolutions": [
        "720p",
        "1080p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 200000
    }
  },
  {
    "id": "veo-3.1-fast",
    "provider": "fal",
    "capability": "video",
    "displayName": "Veo 3.1 Fast",
    "accepts": {
      "referenceImages": 0,
      "startFrame": true,
      "endFrame": false
    },
    "limits": {
      "maxDurationSec": 8,
      "resolutions": [
        "720p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 100000
    }
  },
  {
    "id": "kling-3-pro",
    "provider": "fal",
    "capability": "video",
    "displayName": "Kling Video v3 Text to Video [Pro]",
    "accepts": {
      "referenceImages": 0,
      "startFrame": true,
      "endFrame": true
    },
    "limits": {
      "maxDurationSec": 10,
      "resolutions": [
        "1080p"
      ],
      "aspects": [
        "16:9",
        "9:16",
        "1:1"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 112000
    }
  },
  {
    "id": "kling-3-standard",
    "provider": "fal",
    "capability": "video",
    "displayName": "Kling Video v3 Text to Video [Standard]",
    "accepts": {
      "referenceImages": 0,
      "startFrame": true,
      "endFrame": false
    },
    "limits": {
      "maxDurationSec": 10,
      "resolutions": [
        "720p"
      ],
      "aspects": [
        "16:9",
        "9:16"
      ]
    },
    "pricing": {
      "kind": "perSecond",
      "microUsdPerSecond": 84000
    }
  }
] as const;

/** Model id → fal route. Dispatch needs this; a model without one cannot be submitted. */
export const FAL_ENDPOINTS: Record<string, string> = {
  "flux-2-pro": "fal-ai/flux-2-pro",
  "nano-banana-2": "fal-ai/nano-banana-2",
  "nano-banana-pro": "fal-ai/nano-banana-pro",
  "seedance-2.0": "bytedance/seedance-2.0/text-to-video",
  "seedance-2.0-fast": "bytedance/seedance-2.0/fast/text-to-video",
  "veo-3.1": "fal-ai/veo3.1",
  "veo-3.1-fast": "fal-ai/veo3.1/fast",
  "kling-3-pro": "fal-ai/kling-video/v3/pro/text-to-video",
  "kling-3-standard": "fal-ai/kling-video/v3/standard/text-to-video"
};
